import Head from 'next/head'
import Script from 'next/script'

export default function ServiceCisoPage() {

  return (
    <>
      <Head>
        <title>CISO as a Service — SecComply</title>
        <meta name="description" content="Strategic security leadership when you need it, without the full-time cost." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />




</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> CISO as a Service</div><h1><span class="accent">CISO</span> as a <span class="green">Service</span></h1><p class="hero-sub">Strategic security leadership when you need it, without the full-time cost of an in-house CISO.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x1F4CA;</div><h3>Security Strategy</h3><p>Develop and maintain a comprehensive cybersecurity strategy aligned with business objectives.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x26A0;&#xFE0F;</div><h3>Risk Management</h3><p>Enterprise risk assessment, management, and board-level reporting.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x1F465;</div><h3>Executive Leadership</h3><p>Represent security at the executive and board level with clear communication.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x1F6E1;&#xFE0F;</div><h3>Compliance Oversight</h3><p>Oversee all compliance programs across multiple frameworks.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F50D;</div><h3>Incident Management</h3><p>Lead incident response planning, testing, and execution.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x1F393;</div><h3>Team Development</h3><p>Build and mentor your internal security team capabilities.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Assessment & Onboarding</h3><p>Understand your business, assess current security posture and team capabilities.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>Strategy Development</h3><p>Create a comprehensive security roadmap aligned with business goals.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>Implementation Oversight</h3><p>Guide implementation of security controls and compliance programs.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Ongoing Leadership</h3><p>Regular executive reporting, risk management, and strategic guidance.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Team Building</h3><p>Develop internal capabilities to eventually reduce external dependency.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">How many hours per week/month? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Engagement models are flexible — from 10 hours/month advisory to full-time fractional CISO roles.</div></div></div><div class="faq-item"><button class="faq-question">Can a vCISO replace a full-time CISO? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">For many organizations, especially startups and mid-size companies, a vCISO provides equivalent strategic leadership at a fraction of the cost.</div></div></div><div class="faq-item"><button class="faq-question">What industries do you serve? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">We serve FinTech, SaaS, Healthcare, EdTech, E-commerce, and D2C companies across India and globally.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">CISO as a Service?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a><a href="/pricing" class="btn btn-outline btn-lg">See Pricing <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
      <Script src="/assets/js/effects.js" strategy="afterInteractive" />
    </>
  )
}
