import Head from 'next/head'
import Script from 'next/script'

export default function ServiceDpdpPage() {

  return (
    <>
      <Head>
        <title>DPDP Act Compliance — SecComply</title>
        <meta name="description" content="India\'s Digital Personal Data Protection Act compliance support." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />



</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> DPDP Act</div><h1><span class="accent">DPDP Act</span> <span class="green">Compliance</span></h1><p class="hero-sub">India's Digital Personal Data Protection Act compliance support — from assessment to implementation.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x1F4CB;</div><h3>Compliance Assessment</h3><p>Comprehensive assessment of your data processing activities against DPDP Act requirements.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x1F4DC;</div><h3>Policy Development</h3><p>Data protection policies, consent mechanisms, and privacy notices aligned with the Act.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x26A0;&#xFE0F;</div><h3>Breach Procedures</h3><p>Incident response and data breach notification procedures as per DPDP requirements.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x1F465;</div><h3>DPO Appointment</h3><p>Data Protection Officer appointment guidance and responsibility framework.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F4BE;</div><h3>Data Mapping</h3><p>Comprehensive data inventory and processing activity mapping.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x1F393;</div><h3>Staff Training</h3><p>DPDP Act awareness training for all employees handling personal data.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Data Discovery & Mapping</h3><p>Identify all personal data processing activities across the organization.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>Gap Assessment</h3><p>Evaluate current practices against DPDP Act requirements.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>Policy & Process Development</h3><p>Create compliant policies, consent mechanisms, and procedures.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Implementation & Training</h3><p>Deploy controls, train staff, and integrate compliance into operations.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Ongoing Compliance</h3><p>Continuous monitoring, annual reviews, and regulatory update support.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">Who does the DPDP Act apply to? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">The DPDP Act applies to all organizations that process digital personal data within India, or process data of Indian residents.</div></div></div><div class="faq-item"><button class="faq-question">What are the penalties for non-compliance? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">The DPDP Act provides for significant financial penalties, with amounts varying based on the nature and severity of the violation.</div></div></div><div class="faq-item"><button class="faq-question">Do we need a Data Protection Officer? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Certain categories of Data Fiduciaries classified as Significant Data Fiduciaries are required to appoint a DPO.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">DPDP Compliance?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a><a href="/pricing" class="btn btn-outline btn-lg">See Pricing <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
    </>
  )
}
