import Head from 'next/head'
import Script from 'next/script'

export default function ServiceGdprPage() {

  return (
    <>
      <Head>
        <title>GDPR Compliance Support — SecComply</title>
        <meta name="description" content="Comprehensive GDPR compliance services for EU operations." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />



</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> GDPR</div><h1><span class="accent">GDPR</span> Compliance <span class="green">Support</span></h1><p class="hero-sub">Comprehensive GDPR compliance services for EU operations — from assessment to ongoing management.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x1F4CB;</div><h3>GDPR Assessment</h3><p>Full assessment of data processing activities against GDPR Articles and Recitals.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x1F6E1;&#xFE0F;</div><h3>Data Protection Strategy</h3><p>Comprehensive data protection strategy aligned with GDPR principles.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x1F4DC;</div><h3>DPIA Support</h3><p>Data Protection Impact Assessments for high-risk processing operations.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x1F4BE;</div><h3>ROPA Development</h3><p>Record of Processing Activities documentation and maintenance.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F465;</div><h3>DPO Support</h3><p>Data Protection Officer appointment and ongoing advisory.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x26A0;&#xFE0F;</div><h3>Breach Response</h3><p>GDPR-compliant breach notification procedures and response planning.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Data Audit & Mapping</h3><p>Comprehensive audit of all personal data processing activities.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>Gap Assessment</h3><p>Identify compliance gaps against GDPR requirements.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>Policy & Documentation</h3><p>Privacy policies, consent frameworks, ROPA, and DPIAs.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Implementation</h3><p>Technical and organizational measures implementation.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Ongoing Compliance</h3><p>Continuous monitoring, DPO support, and regulatory updates.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">Does GDPR apply to my Indian company? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">GDPR applies if you offer goods/services to EU residents or monitor their behavior, regardless of your location.</div></div></div><div class="faq-item"><button class="faq-question">What's the penalty for GDPR non-compliance? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Penalties can reach up to €20 million or 4% of annual global turnover, whichever is higher.</div></div></div><div class="faq-item"><button class="faq-question">Do we need a DPO under GDPR? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">A DPO is required if you're a public authority, engage in large-scale systematic monitoring, or process special categories of data at scale.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">GDPR Compliance?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a><a href="/pricing" class="btn btn-outline btn-lg">See Pricing <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
    </>
  )
}
