import Head from 'next/head'
import Script from 'next/script'

export default function ServiceIso27701Page() {

  return (
    <>
      <Head>
        <title>ISO/IEC 27701 Privacy Information Management — SecComply</title>
        <meta name="description" content="Comprehensive privacy information management system implementation." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />



</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> ISO 27701</div><h1><span class="accent">ISO/IEC 27701</span> Privacy Information <span class="green">Management</span></h1><p class="hero-sub">Comprehensive privacy information management system implementation extending your ISO 27001 ISMS.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x1F512;</div><h3>Privacy Gap Analysis</h3><p>Identify gaps in your current privacy practices against ISO 27701 requirements.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x1F4CB;</div><h3>PIMS Design</h3><p>Design a Privacy Information Management System extending your existing ISMS.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x1F6E1;&#xFE0F;</div><h3>Privacy Controls</h3><p>Implement PII controller and processor controls as per Annex A and B.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x1F4DC;</div><h3>DPIA Support</h3><p>Data Protection Impact Assessments for high-risk processing activities.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F310;</div><h3>Regulatory Mapping</h3><p>Map controls to GDPR, DPDP Act, and other privacy regulations.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x1F50E;</div><h3>Certification Support</h3><p>Full audit preparation and certification body liaison support.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Privacy Assessment</h3><p>Evaluate current privacy practices and data processing activities.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>PIMS Design</h3><p>Design the Privacy Information Management System extending ISO 27001.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>Control Implementation</h3><p>Implement PII controller and processor controls per Annex A/B.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Documentation & Training</h3><p>Privacy policy development, ROPA, and staff privacy training.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Audit & Certification</h3><p>Internal audit and certification body audit preparation.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">Do I need ISO 27001 first? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Yes, ISO 27701 is an extension to ISO 27001. You need an existing ISMS to implement ISO 27701.</div></div></div><div class="faq-item"><button class="faq-question">How does ISO 27701 relate to GDPR? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">ISO 27701 provides a framework that maps directly to GDPR requirements, making compliance demonstration easier.</div></div></div><div class="faq-item"><button class="faq-question">What's the timeline for ISO 27701? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">If you already have ISO 27001, typically 4-6 weeks for ISO 27701 implementation.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">ISO 27701 Certification?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a><a href="/pricing" class="btn btn-outline btn-lg">See Pricing <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
    </>
  )
}
