import Head from 'next/head'
import Script from 'next/script'

export default function ServiceIso27001Page() {

  return (
    <>
      <Head>
        <title>ISO 27001 Consulting & Implementation — SecComply</title>
        <meta name="description" content="Complete ISO 27001 certification support from gap analysis to audit readiness." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />




</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> ISO 27001</div><h1><span class="accent">ISO 27001</span> Consulting &amp; <span class="green">Implementation</span></h1><p class="hero-sub">Complete ISO 27001 certification support from gap analysis to audit readiness. Get certified in 4-8 weeks.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/?ismsaljsauthenabled" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x1F50D;</div><h3>Gap Assessment</h3><p>Comprehensive analysis of your current security posture against ISO 27001 requirements.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x2699;&#xFE0F;</div><h3>ISMS Implementation</h3><p>End-to-end Information Security Management System design, documentation, and implementation.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x1F4CB;</div><h3>Policy Development</h3><p>Custom security policies and procedures that meet ISO 27001 requirements.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x26A0;&#xFE0F;</div><h3>Risk Assessment</h3><p>Thorough risk identification, analysis, and treatment aligned with Annex A controls.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F393;</div><h3>Staff Training</h3><p>Security awareness training and ISMS operation training for your team.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x1F50E;</div><h3>Audit Support</h3><p>Complete Stage 1 and Stage 2 audit preparation and auditor liaison support.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Scoping & Gap Analysis</h3><p>Assess current security posture, define ISMS scope, identify gaps against ISO 27001:2022.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>Risk Assessment & Treatment</h3><p>Risk identification, analysis, evaluation, and treatment plan with Annex A mapping.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>ISMS Design & Documentation</h3><p>Policy creation, Statement of Applicability, and complete ISMS documentation.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Implementation & Training</h3><p>Control implementation, staff awareness training, operational integration.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Internal Audit & Certification</h3><p>Internal audit, management review, Stage 1 & Stage 2 audit support.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">How long does ISO 27001 certification take? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">With SecComply, most organizations achieve certification readiness in 4-8 weeks depending on size and complexity.</div></div></div><div class="faq-item"><button class="faq-question">What is the cost of ISO 27001 certification? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Cost depends on organization size, scope, number of locations, and current maturity. Contact us for a transparent quote.</div></div></div><div class="faq-item"><button class="faq-question">Do we need ISO 27001 if we already have SOC 2? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">ISO 27001 is internationally recognized and many global clients require it. Having both demonstrates comprehensive security commitment.</div></div></div><div class="faq-item"><button class="faq-question">What version of ISO 27001 do you implement? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">We implement ISO 27001:2022 with 93 Annex A controls in 4 categories: Organizational, People, Physical, and Technological.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">ISO 27001 Certification?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/?ismsaljsauthenabled" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
      <Script src="/assets/js/effects.js" strategy="afterInteractive" />
    </>
  )
}
