import Head from 'next/head'
import Script from 'next/script'

export default function ServiceSoc2Page() {

  return (
    <>
      <Head>
        <title>SOC 2 Type I & Type II Readiness — SecComply</title>
        <meta name="description" content="Comprehensive SOC 2 compliance preparation and ongoing monitoring." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />




</Head>
      <div dangerouslySetInnerHTML={{__html: `<section class="service-hero"><div class="hero-grid"></div><div class="hero-glow hero-glow-1"></div><div class="hero-glow hero-glow-2"></div><div class="hero-glow-center"></div><div class="hero-glow-ring"></div><div class="container"><div class="hero-content"><div class="hero-badge"><span class="hero-badge-dot"></span> SOC 2</div><h1><span class="accent">SOC 2</span> Type I &amp; Type II <span class="green">Readiness</span></h1><p class="hero-sub">Comprehensive SOC 2 compliance preparation and ongoing monitoring. Get audit-ready with zero nonconformities.</p><div class="hero-ctas"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
<section class="benefits-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Key Benefits</div><h2 class="section-title">Why Choose SecComply?</h2></div><div class="benefits-grid"><div class="feature-card reveal delay-1"><div class="feature-icon orange">&#x2699;&#xFE0F;</div><h3>Control Design</h3><p>Design and implement controls across Trust Services Criteria: Security, Availability, Confidentiality, PI, Processing Integrity.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon green">&#x1F4CE;</div><h3>Evidence Collection</h3><p>Systematic evidence gathering and organization for all control objectives.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon blue">&#x1F50E;</div><h3>Audit Preparation</h3><p>Complete readiness assessment and CPA firm liaison for smooth audits.</p></div><div class="feature-card reveal delay-1"><div class="feature-icon purple">&#x1F4CA;</div><h3>Gap Remediation</h3><p>Identify and fix compliance gaps before the formal audit begins.</p></div><div class="feature-card reveal delay-2"><div class="feature-icon teal">&#x1F4CB;</div><h3>Policy Framework</h3><p>SOC 2-aligned security policies, procedures, and documentation.</p></div><div class="feature-card reveal delay-3"><div class="feature-icon orange">&#x1F504;</div><h3>Continuous Monitoring</h3><p>Ongoing compliance monitoring between Type I and Type II audit periods.</p></div></div></div></section>
<section class="timeline-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> Process</div><h2 class="section-title">Our Process</h2></div><div class="timeline"><div class="timeline-item reveal delay-1"><div class="timeline-dot"></div><h3>Scoping & TSC Selection</h3><p>Define audit scope and select applicable Trust Services Criteria.</p></div><div class="timeline-item reveal delay-2"><div class="timeline-dot"></div><h3>Gap Assessment</h3><p>Identify current control gaps against SOC 2 requirements.</p></div><div class="timeline-item reveal delay-3"><div class="timeline-dot"></div><h3>Control Implementation</h3><p>Design and implement controls to address identified gaps.</p></div><div class="timeline-item reveal delay-4"><div class="timeline-dot"></div><h3>Evidence Collection</h3><p>Systematic evidence gathering for all control objectives.</p></div><div class="timeline-item reveal delay-5"><div class="timeline-dot"></div><h3>Audit Readiness & Support</h3><p>Pre-audit readiness review and CPA auditor liaison.</p></div></div></div></section>
<section class="faq-section"><div class="container"><div class="section-header reveal"><div class="section-badge"><span class="section-badge-dot"></span> FAQ</div><h2 class="section-title">Frequently Asked Questions</h2></div><div class="faq-list"><div class="faq-item"><button class="faq-question">What's the difference between Type I and Type II? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Type I evaluates control design at a point in time. Type II evaluates both design and operating effectiveness over a period (typically 3-12 months).</div></div></div><div class="faq-item"><button class="faq-question">How long does SOC 2 preparation take? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Type I readiness typically takes 4-6 weeks. Type II requires an additional observation period of 3-12 months.</div></div></div><div class="faq-item"><button class="faq-question">Which Trust Services Criteria do we need? <span class="faq-icon">+</span></button><div class="faq-answer"><div class="faq-answer-inner">Security is mandatory. Availability, Confidentiality, Processing Integrity, and Privacy are selected based on your service commitments.</div></div></div></div></div></section>
<section class="cta-section"><div class="cta-glow-1"></div><div class="cta-glow-2"></div><div class="container"><div class="cta-content reveal"><h2>Ready for <span class="accent">SOC 2 Compliance?</span></h2><p>Book a free 15-minute consultation to discuss your compliance needs.</p><div class="cta-buttons"><a href="https://outlook.office.com/book/SecComplyMeeting1@seccomply.net/" class="btn btn-primary btn-lg" target="_blank">Book Free Consultation <span class="btn-icon">&rarr;</span></a></div></div></div></section>
`}} />
<Script src="/assets/js/animations.js" strategy="afterInteractive" />
      <Script src="/assets/js/counters.js" strategy="afterInteractive" />
      <Script src="/assets/js/accordion.js" strategy="afterInteractive" />
      <Script src="/assets/js/effects.js" strategy="afterInteractive" />
    </>
  )
}
