import Head from 'next/head'
import Link from 'next/link'
import Layout from '../../../components/Layout'

const posts = [
  { slug: 'iso-27701-annex-a-controls', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 Annex A Controls — A Plain-English Walkthrough for Teams', desc: "Annex A & B controls explained — 8 thematic areas for controllers and processors, key actions for each team, RACI ownership, and practical implementation tips.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '10 min read' },
  { slug: 'consent-under-dpdp-act', icon: '🇮🇳', tag: 'DPDP Act', title: "Consent Under the DPDP Act — What's Valid, What's Not, and How to Implement It", desc: "Section 6 of the DPDP Act sets out 5 non-negotiable pillars of valid consent. Pre-ticked boxes, bundled consent, and vague language will not pass the test. Here is the technical blueprint for DPDP-compliant consent.", author: 'Chandrika Mulage', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-scope-definition', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Scope Definition — How to Decide What Goes In and What Stays Out', desc: "The ISMS scope is the most consequential decision before starting ISO 27001. Too broad costs time. Too narrow leaves gaps. Scope examples for SaaS, FinTech, Healthcare, and consulting firms.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-risk-assessment', icon: '🌍', tag: 'ISO 27001', title: 'Risk Assessment in ISO 27001 — How It Works Step by Step', desc: "The risk assessment is the engine of the ISMS. Step-by-step methodology — asset identification, threat analysis, likelihood-impact scoring, risk treatment, and the risk register with common startup risks.", author: 'Soham Sawant', date: 'April 2026', read: '9 min read' },
  { slug: 'iso-27701-for-data-processors', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 for Data Processors — What Third Parties Need to Know', desc: "Clause 9 requirements for data processors — DPAs, sub-processor management, breach notification timelines, Privacy by Design obligations, and the step-by-step certification path.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '12 min read' },
  { slug: '8-rights-data-principals-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: '8 Rights of Data Principals Under the DPDP Act — And How Your Product Must Support Them', desc: "The DPDP Act grants 8 enforceable rights to Data Principals. Failing to operationalise them exposes your organisation to penalties up to ₹250 crore. Here is what each right requires in product terms.", author: 'Chandrika Mulage', date: 'April 2026', read: '9 min read' },
  { slug: 'iso-27001-annex-a-controls', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Annex A Controls — All 93 Controls Explained Simply', desc: "93 controls in 4 categories: Organisational (37), People (8), Physical (14), Technological (34). What each covers, the 11 new 2022 controls, how the Statement of Applicability works, and startup priority controls.", author: 'Soham Sawant', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27701-for-data-controllers', icon: '🌐', tag: 'ISO 27701', title: 'ISO 27701 for Data Controllers — Key Requirements and Controls Explained', desc: "If your organisation decides what data to collect, why, and how — you are a PII controller. Clause 7 and Annex B controls in operational detail — legal basis, RoPA, consent, DSR rights, DPIAs, and privacy by design.", author: 'Aditya Hadke', date: 'April 2026', read: '12 min read' },
  { slug: 'data-principal-fiduciary-processor', icon: '🇮🇳', tag: 'DPDP Act', title: "Data Principal vs Data Fiduciary vs Data Processor — Roles Explained Under India's DPDP Act", desc: "The DPDP Act introduces three roles — Data Principal, Data Fiduciary, and Data Processor. Understand who you are in the data ecosystem, what obligations apply, and what happens when one entity holds multiple roles.", author: 'Chandrika Mulage', date: 'April 2026', read: '7 min read' },
  { slug: 'iso-27001-business-value', icon: '🌍', tag: 'ISO 27001', title: 'The Real Business Value of ISO 27001 Certification — Beyond the Badge', desc: "ISO 27001 is not a compliance cost — it is a commercial asset. Enterprise sales acceleration (40% faster), breach cost reduction, 25-30% lower insurance premiums, investor due diligence, and the ROI calculation.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'how-to-extend-isms-into-pims', icon: '🔐', tag: 'ISO 27701', title: 'How to Extend Your ISMS Into a PIMS — ISO 27001 + ISO 27701', desc: "Most organisations with ISO 27001 have done 50-70% of the ISO 27701 work already. The 7-step extension process, documentation auditors expect, combined vs phased certification, and a PIMS readiness checklist.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '8 min read' },
  { slug: 'what-is-personal-data-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: 'What Counts as Personal Data Under the DPDP Act?', desc: "The DPDP Act's definition is deliberately broad. If you are assuming only Aadhaar or medical records are in scope, you have serious gaps. The breakdown your product and engineering teams need — including the grey zones.", author: 'Chandrika Mulage', date: 'April 2026', read: '6 min read' },
  { slug: 'what-is-an-isms', icon: '🌍', tag: 'ISO 27001', title: 'What Is an ISMS? Information Security Management System in Plain English', desc: "An ISMS is not a product, a document, or a one-time project. It is a management system — the PDCA cycle, core components, scope definition, risk assessment, controls, audit, and what an ISMS is NOT.", author: 'Soham Sawant', date: 'April 2026', read: '7 min read' },
  { slug: 'building-a-pims-iso-27701', icon: '🌐', tag: 'ISO 27701', title: 'Building a PIMS — ISO 27701 Implementation Roadmap', desc: "A practical 6-phase roadmap to implement ISO 27701 and build a Privacy Information Management System — from scoping to certification, with realistic timelines, budgets, and common pitfalls.", author: 'Aditya Hadke', date: 'April 2026', read: '10 min read' },
  { slug: 'who-does-dpdp-apply-to', icon: '🇮🇳', tag: 'DPDP Act', title: 'Who Does the DPDP Act Apply To? — A Checklist for Indian Businesses', desc: "For the vast majority of Indian businesses, yes — but the specifics depend on your role, your data, and who your users are. A plain-English checklist plus industry snapshots for SaaS, Fintech, Healthtech, EdTech, and HR software.", author: 'Chandrika Mulage', date: 'April 2026', read: '6 min read' },
  { slug: 'what-counts-personal-data-gdpr', icon: '🇪🇺', tag: 'GDPR', title: 'What Counts as Personal Data Under GDPR? With Real Examples', desc: "The short answer: more than you think. IP addresses, cookie IDs, device IDs, pseudonymous tokens, voice recordings, work emails — all personal data. The surprise table, the combination trap, and anonymous vs pseudonymous.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'iso-27001-vs-soc2-vs-gdpr', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 vs SOC 2 vs GDPR — Key Differences Every Business Should Know', desc: "ISO 27001 is a certification. SOC 2 is an attestation report. GDPR is a law. Detailed comparison — scope, geography, cost, audit process, 60-70% control overlap, and which to pursue first.", author: 'Soham Sawant', date: 'April 2026', read: '9 min read' },
  { slug: 'who-needs-iso-27701', icon: '🌐', tag: 'ISO 27701', title: 'Who Needs ISO 27701? — Applicability Guide for Controllers and Processors', desc: "ISO 27701 is applicable to any organisation processing PII. The controller vs processor distinction, industry-by-industry guidance for SaaS, FinTech, Healthtech, and MSPs, plus when formal certification is worth it.", author: 'Aditya Hadke', date: 'April 2026', read: '11 min read' },
  { slug: 'gdpr-vs-dpdp', icon: '⚖️', tag: 'DPDP Act', title: 'GDPR vs DPDP Act: Key Differences Every Indian Company Must Know', desc: "Already GDPR-compliant and treating DPDP as basically the same thing? The lawful basis gap, rights comparison, 22-language requirement, children's threshold at 18, and your exact gap list.", author: 'SecComply', date: 'March 2026', read: '7 min read' },
  { slug: 'gdpr-self-assessment', icon: '🇪🇺', tag: 'GDPR', title: 'Does GDPR Apply to Your Business? A Self-Assessment Guide', desc: "An 8-question self-assessment for startups and SMBs. Score your GDPR exposure, debunk the four exemption myths (no SMB exemption, B2B data is still personal data), and follow the 30-day action plan.", author: 'Gauri Khatate', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27001-self-assessment', icon: '✅', tag: 'ISO 27001', title: 'Does ISO 27001 Apply to Your Business? A Self-Assessment Guide', desc: "Work through 6 triggers to decide whether ISO 27001 applies right now — enterprise customers, international expansion, sensitive data, investor due diligence, DPDP Act, and prior incidents. Includes a scoring guide and 5-phase roadmap.", author: 'Soham Sawant', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27701-vs-gdpr-vs-dpdp', icon: '🌐', tag: 'ISO 27701', title: 'ISO 27701 vs GDPR vs DPDP — How They Overlap and Where They Differ', desc: "A SaaS company in India processing EU and Indian data faces three frameworks simultaneously. The detailed comparison — cross-border transfers, consent, breach timelines, and how to run a single unified compliance programme.", author: 'Aditya Hadke', date: 'April 2026', read: '13 min read' },
  { slug: 'dpdp-act-2023-explained', icon: '🇮🇳', tag: 'DPDP Act', title: 'DPDP Act 2023 Explained in Plain English', desc: "India's data privacy law is now enforceable. Who it applies to (no size threshold), 5 core obligations, the penalty schedule up to ₹250 crore, the 4 terms you must know, and your first 30 days action plan.", author: 'SecComply', date: 'March 2026', read: '7 min read' },
  { slug: 'gdpr-explained-startups', icon: '🇪🇺', tag: 'GDPR', title: "GDPR Explained for Startups — What It Is, Why It Matters, and What You Must Do About It", desc: "Most founders think GDPR applies only at scale. The fines say otherwise. Six principles, controller vs processor, eight user rights, the consent trap, real-world cases (Spotify, Meta, Clearview AI), and the practical startup checklist.", author: 'Gauri Khatate', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-explained-startups', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Explained for Startups — What It Is and Why It Matters', desc: "Enterprise customers ask for it. Investors flag it in due diligence. What ISO 27001 actually requires, the 93 Annex A controls, the 5-phase certification process, realistic cost (₹8–25L) and timeline (4–9 months), and ISO 27001 vs SOC 2.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'iso-27701-explained', icon: '🔐', tag: 'Privacy Compliance', title: 'ISO 27701 Explained: Privacy Information Management for Compliance Teams', desc: "ISO 27701 is the privacy extension to ISO 27001. What a PIMS requires, PII controller vs processor controls, the RoPA, privacy by design, data subject rights, regulatory mapping to GDPR and DPDP, and a 6-9 month implementation roadmap.", author: 'Aditya Hadke', date: 'March 2026', read: '12 min read' },
  { slug: 'significant-data-fiduciary-sdf', icon: '🇮🇳', tag: 'DPDP Act', title: 'Significant Data Fiduciary (SDF) — Are You One? What Changes If You Are?', desc: "Section 10 of the DPDP Act reserves a higher tier of obligations for entities handling data at scale. Learn how the government classifies SDFs, the 4 additional obligations that apply, and how to self-assess your SDF exposure.", author: 'Chandrika Mulage', date: 'April 2026', read: '8 min read' },
  { slug: 'data-protection-officer-dpo-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: 'What Is a Data Protection Officer (DPO) Under the DPDP Act — Do You Need One?', desc: "The DPO role under the DPDP Act is structured, targeted, and demanding — but only mandatory for Significant Data Fiduciaries. The full picture on the role, reporting structure, India-presence requirement, and when you need one.", author: 'Chandrika Mulage', date: 'April 2026', read: '7 min read' },
  { slug: 'dpdp-applicability-quiz-walkthrough', icon: '🇮🇳', tag: 'DPDP Act', title: "\"Do I Need to Comply?\" — DPDP Act Applicability Quiz Walkthrough", desc: "A structured 7-question walkthrough to self-assess DPDP Act applicability and your compliance tier. Covers exemptions, volume thresholds, cross-border considerations, and an immediate action plan.", author: 'Chandrika Mulage', date: 'April 2026', read: '9 min read' },
  { slug: 'grc-automation', icon: '⚙️', tag: 'Compliance Governance', title: 'GRC Automation: The Future of Compliance', desc: "The compliance team that runs on spreadsheets is running a programme designed for 2010. What GRC automation actually does, what it cannot replace, how to evaluate platforms (Vanta, Drata, Sprinto, Secureframe), and when to invest.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'supply-chain-attacks-solarwinds', icon: '🔗', tag: 'Supply Chain Security', title: 'Supply Chain Attacks: Lessons from SolarWinds', desc: "18,000 organisations downloaded a backdoor disguised as a routine update. The full kill chain, 14-month dwell time, 6 lessons every security team must apply, the SBOM imperative, and what your controls must look like now.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'vulnerability-disclosure-policy', icon: '🔍', tag: 'Security Governance', title: 'How to Build a Vulnerability Disclosure Policy', desc: "Every day researchers find vulnerabilities in systems they don't own. Without a VDP they have no safe way to tell you. Scope, safe harbour clause, security.txt file, triage SLAs, and ISO 27001 compliance mapping.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'how-to-write-security-policy', icon: '📋', tag: 'Security Governance', title: 'How to Write a Security Policy People Will Actually Follow', desc: "Most security policies are written to satisfy auditors, not change behaviour. The 6-step process, before/after language rewrites, 8 policy types, enforcement mechanisms, and compliance mapping for ISO 27001, SOC 2, and DPDP.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'owasp-top-10-2025', icon: '🔓', tag: 'AppSec', title: 'OWASP Top 10 — 2025 Edition Breakdown', desc: "All 10 categories with CWE references, real-world examples, fix guidance, and compliance mapping. SSRF elevated to standalone category. AI-generated code security guidance added for the first time.", author: 'Soham Sawant', date: 'March 2026', read: '10 min read' },
  { slug: 'tprm-best-practices', icon: '🔗', tag: 'Vendor Risk', title: 'Third-Party Risk Management Best Practices', desc: "62% of breaches are traced to a third party. Vendor tiering, access scoping, contractual controls, continuous monitoring, and the offboarding gap. With Target, Okta, British Airways, and M&S breach cases.", author: 'Gauri Khatate', date: 'March 2026', read: '7 min read' },
  { slug: 'red-team-vs-blue-team', icon: '🔴', tag: 'Security Testing', title: "Red Team vs Blue Team: What's the Difference and Why You Need Both", desc: "Four real-world breach cases, the Purple Team model, MTTD improvement, and how to decide which your organisation needs first.", author: 'Gauri Khatate', date: 'March 2026', read: '7 min read' },
  { slug: 'tabletop-security-exercise', icon: '🎯', tag: 'Incident Response', title: 'How to Run a Tabletop Security Exercise', desc: "77% of organisations that suffered a breach had no tested IR plan. Scenario selection, 6 ransomware injects, participant roles, debrief structure, and compliance evidence for ISO 27001, SOC 2, and HIPAA.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'phishing-simulation-guide', icon: '🎣', tag: 'Security Awareness', title: 'Phishing Simulation: A Step-by-Step Guide', desc: "36% of all breaches involve phishing. A well-run simulation cuts click rates by 80% in 12 months. The 7-step process, 5 template types, 4 metrics, and the compliance evidence auditors actually want.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'encryption-at-rest-vs-in-transit', icon: '🔐', tag: 'Data Security', title: 'Encryption at Rest vs In Transit: What You Must Know', desc: "AES-256 vs TLS 1.3, key management done right, compliance requirements across 6 frameworks, and the implementation mistakes that get organisations into trouble with auditors.", author: 'Soham Sawant', date: 'March 2026', read: '7 min read' },
  { slug: 'cspm-aws', icon: '☁️', tag: 'Cloud Security', title: 'Cloud Security Posture Management for AWS', desc: "99% of cloud breaches stem from misconfiguration. What CSPM does on AWS, the top misconfigurations it catches, ISO 27001 and SOC 2 compliance mapping, and a 5-step implementation guide.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'ciso-startup-guide', icon: '🛡️', tag: 'Security Leadership', title: 'The Role of a CISO in a Startup', desc: "Most startups think they need a CISO when they get hacked. The ones that get it right hire one so they never do. What a CISO actually does, when to hire one, and the full-time vs vCISO breakdown.", author: 'Soham Sawant', date: 'June 2025', read: '5 min read' },
  { slug: 'devsecops-shifting-left', icon: '⚙️', tag: 'DevSecOps', title: 'DevSecOps: Shifting Security Left Without Slowing Down', desc: "3 pillars, the complete automation stack (SAST, SCA, DAST, IaC), STRIDE threat modeling, compliance integration, and a 3-phase maturity roadmap.", author: 'Aditya Hadke', date: 'March 2025', read: '12 min read' },
  { slug: 'how-to-prepare-for-a-security-audit', icon: '🔍', tag: 'Audit Readiness', title: 'How to Prepare for a Security Audit', desc: "8 stages, the evidence auditors actually look for, and a pre-audit checklist covering ISO 27001, SOC 2, DPDPA, and GDPR.", author: 'Bhumika Deshmukh', date: 'March 2026', read: '7 min read' },
  { slug: 'security-metrics-board-reporting', icon: '📊', tag: 'Security Governance', title: 'Security Metrics That Actually Matter to the Board', desc: "Six metric categories, five governance questions, and the reporting principles that change what happens in that boardroom.", author: 'Bhumika Deshmukh', date: 'March 2026', read: '8 min read' },
  { slug: 'sbom-software-bill-of-materials', icon: '📦', tag: 'Supply Chain Security', title: 'SBOM 101: Why Software Bills of Materials Matter', desc: 'Log4Shell exposed 625,000+ apps using a library nobody knew they had. What SBOMs are, SPDX vs CycloneDX, and how to generate one today.', author: 'Soham Sawant', date: 'March 20, 2026', read: '8 min read' },
  { slug: 'vulnerability-management-startups', icon: '🔍', tag: 'Vulnerability Management', title: 'Vulnerability Management for Startups: A Practical Guide', desc: "Core process, CVSS severity framework, free tools, and a 90-day roadmap to audit-readiness without a large security team.", author: 'Aditya Hadke', date: 'March 2026', read: '8 min read' },
  { slug: 'cloud-native-security', icon: '☁️', tag: 'Cloud Security', title: 'Cloud-Native Security: Key Concepts Every Team Must Know', desc: 'From containers to microservices, Zero Trust to DevSecOps — securing modern cloud-native environments across ISO 27001, SOC 2, HIPAA, and GDPR.', author: 'Soham Sawant', date: 'June 2025', read: '6 min read' },
  { slug: 'how-to-evaluate-security-vendor', icon: '🛡️', tag: 'Vendor Risk', title: 'How to Evaluate Your Security Vendor Without Getting Burned', desc: "The right questions, red flags, certifications table, and contract clauses that protect you when things go wrong.", author: 'Aditya Hadke', date: 'March 2026', read: '7 min read' },
  { slug: 'ai-generated-code-security-risks', icon: '🤖', tag: 'AI Security', title: 'AI-Generated Code and Security Risks', desc: '3 in 5 AI code suggestions contain at least one flaw. Where the risk lives and how to build the review layer that makes AI-speed development safe.', author: 'Gauri Khatate', date: 'March 2026', read: '5 min read' },
  { slug: 'top-5-cloud-misconfigurations', icon: '☁️', tag: 'Cloud Security', title: 'Top 5 Cloud Misconfigurations and How to Fix Them', desc: "The five misconfigurations that appear most often in breach investigations, with exact fixes for each.", author: 'Bhumika Deshmukh', date: 'March 11, 2026', read: '7 min read' },
  { slug: 'soc2-type1-vs-type2', icon: '📋', tag: 'SOC 2', title: 'SOC 2 Type I vs Type II — The Distinction That Actually Matters', desc: 'One is a snapshot. The other is proof over time. What separates them and the practical path from one to the other.', author: 'Gauri Khatate', date: 'March 2026', read: '5 min read' },
  { slug: 'top-security-tools-startup', icon: '🔐', tag: 'Security Tools', title: 'Top 10 Security Tools Every Startup Should Know in 2026', desc: 'Ten tools in deployment order, each one closes a SOC 2 gap and builds enterprise trust. Several are free.', author: 'Bhumika Deshmukh', date: 'March 2026', read: '8 min read' },
  { slug: 'soc2-vs-iso27001', icon: '📋', tag: 'Compliance Guide', title: 'SOC 2 vs ISO 27001: Which Certification Should You Choose?', desc: 'Cost, timeline, market fit, and the honest recommendation for Indian startups and SaaS companies expanding globally.', author: 'SecComply', date: 'March 2026', read: '9 min read' },
  { slug: 'what-is-cspm-scan', icon: '☁️', tag: 'Cloud Security', title: 'What is a CSPM Scan? Cloud Security Posture Management Explained', desc: 'How CSPM scans work, what they detect, and how to stay continuously compliant across AWS, Azure, and GCP.', author: 'SecComply', date: 'March 2025', read: '7 min read' },
  { slug: 'skt-breach-compliance-failure', icon: '📡', tag: 'Breach Analysis', title: "SK Telecom Breach: When Compliance Failures Become a $97M Bill", desc: "South Korea's biggest telecom wasn't brought down by a zero-day — it was missing basics. What every organisation should take from the $97M fine.", author: 'SecComply', date: 'March 2026', read: '10 min read' },
  { slug: 'dpdp-act-indian-startups', icon: '🇮🇳', tag: 'DPDP Act', title: 'DPDP Act 2023: What Indian Startups Need to Know', desc: "A breakdown of India's Digital Personal Data Protection Act and practical steps for compliance readiness.", author: 'SecComply', date: 'March 2025', read: '6 min read' },
  { slug: 'top-10-security-controls', icon: '🔒', tag: 'Security Controls', title: 'Top 10 Security Controls Every Startup Should Implement', desc: 'Essential security controls that form the foundation of any compliance program, explained in plain language.', author: 'SecComply', date: 'February 2025', read: '5 min read' },
  { slug: 'cost-of-non-compliance', icon: '💰', tag: 'Compliance', title: 'The True Cost of Non-Compliance in 2025', desc: 'Data-driven analysis of what compliance failures cost companies, from fines to lost deals and reputation damage.', author: 'SecComply', date: 'January 2025', read: '6 min read' },
]
export default function Blog() {
  return (
    <Layout>
      <Head>
        <title>Blog & Insights, SecComply</title>
        <meta name="description" content="Latest insights on cybersecurity, compliance trends, and regulatory updates from the SecComply team." />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/assets/css/resource-pages.css" />
      </Head>

      <style jsx global>{`
        .blog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;max-width:1100px;margin:40px auto 80px;padding:0 24px}
        .blog-card{background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;transition:all .3s ease;text-decoration:none;color:inherit;position:relative;overflow:hidden}
        .blog-card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#E8632B,#FF8A50);transform:scaleX(0);transform-origin:left;transition:transform .4s cubic-bezier(.16,1,.3,1)}
        .blog-card:hover::before{transform:scaleX(1)}
        .blog-card:hover{border-color:rgba(232,99,43,.3);transform:translateY(-4px);box-shadow:0 12px 40px rgba(232,99,43,.1)}
        .blog-tag{display:inline-block;padding:4px 12px;border-radius:20px;font-size:.68rem;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;background:rgba(232,99,43,.12);color:#E8632B;width:fit-content}
        .blog-icon{font-size:1.6rem;line-height:1}
        .blog-card h3{font-size:1rem;font-weight:700;color:#F8FAFC;margin:0;line-height:1.4}
        .blog-card p{font-size:.86rem;color:#94A3B8;line-height:1.6;margin:0;flex:1}
        .blog-meta{font-size:.75rem;color:#64748B;display:flex;align-items:center;gap:8px;flex-wrap:wrap}
        .blog-meta .dot{opacity:.4}
        .blog-cta{color:#E8632B;font-size:.85rem;font-weight:600;display:inline-flex;align-items:center;gap:5px;transition:gap .2s;margin-top:4px}
        .blog-card:hover .blog-cta{gap:9px}
        @media(max-width:900px){.blog-grid{grid-template-columns:repeat(2,1fr)}}
        @media(max-width:600px){.blog-grid{grid-template-columns:1fr;padding:0 16px}}
      `}</style>

      <section className="sub-hero">
        <Link href="/resources" className="sub-back">← Back to Resources</Link>
        <h1>📝 Blog & Insights</h1>
        <p>Latest insights on cybersecurity, compliance trends, and regulatory updates.</p>
      </section>

      <div className="blog-grid">
        {posts.map((post) => (
          <Link key={post.slug} href={'/resources/blog/' + post.slug} className="blog-card">
            <span className="blog-tag">{post.tag}</span>
            <div className="blog-icon">{post.icon}</div>
            <h3>{post.title}</h3>
            <p>{post.desc}</p>
            <div className="blog-meta">
              <span>{post.author}</span>
              <span className="dot">·</span>
              <span>{post.date}</span>
              <span className="dot">·</span>
              <span>{post.read}</span>
            </div>
            <span className="blog-cta">Read article →</span>
          </Link>
        ))}
      </div>
    </Layout>
  )
}