import Head from 'next/head'
import Link from 'next/link'
import Layout from '../../../components/Layout'

const posts = [
  { slug: 'hipaa-compliance-roadmap', icon: '🏥', tag: 'HIPAA', title: 'HIPAA Compliance Roadmap - A Step-by-Step Guide for HealthTech Teams', desc: "There is no HIPAA certificate — compliance is a state you build, run, and can prove. Seven steps in the order that works: fix your role and map the PHI, run the risk analysis (OCR's most-cited failure), implement the safeguards, put policies and BAAs in place, train, rehearse the breach, and keep it alive. With a realistic 90-day timeline.", author: 'Soham Sawant', date: 'July 7, 2026', read: '9 min read' },
  { slug: 'hipaa-patient-rights', icon: '🏥', tag: 'HIPAA', title: 'Patient Rights Under HIPAA - Access, Amendment, and Accounting of Disclosures', desc: "Most of HIPAA is written at organisations; the rights are written at people — and they arrive as real requests with statutory deadlines. Access in 30 days, amendment decisions in 60, six years of disclosures on demand. The mechanics of each, OCR's Right of Access enforcement, and the export, correction, and logging features they quietly require.", author: 'Soham Sawant', date: 'July 6, 2026', read: '8 min read' },
  { slug: 'hipaa-business-associate-agreement', icon: '🏥', tag: 'HIPAA', title: 'Business Associate Agreements (BAA) - What They Must Include and Why', desc: "The BAA is the only contract a federal privacy law forces you to sign — and its absence is a violation all by itself, no breach required. Every provision 45 CFR 164.504(e) demands, the negotiated terms that become engineering requirements, the subcontractor flow-down, and the OCR settlements — up to $1.55M — for the missing document.", author: 'Soham Sawant', date: 'July 5, 2026', read: '8 min read' },
  { slug: 'hipaa-minimum-necessary-standard', icon: '🏥', tag: 'HIPAA', title: 'HIPAA Minimum Necessary Standard - What It Means for Product Teams', desc: "Holding a record doesn't entitle you — or your features — to read all of it. What 45 CFR 164.502(b) actually requires, the three triggers and six exceptions, and how the standard becomes RBAC, field-scoped APIs, de-identified analytics, and PHI-free logs. Least privilege for data, written into law in 2000.", author: 'Soham Sawant', date: 'July 4, 2026', read: '8 min read' },
  { slug: 'hipaa-vs-gdpr-vs-dpdp', icon: '🏥', tag: 'HIPAA', title: 'HIPAA vs GDPR vs DPDP - Key Differences for Global Health Platforms', desc: "A patient record can be regulated by three laws at once - a US sectoral rule, an EU omnibus regulation, and India's consent-first act. HIPAA regulates a sector, GDPR a data type, DPDP consent. What each governs, how they treat health data differently (GDPR's special category vs DPDP's none), and how to build one security core with three privacy overlays.", author: 'Soham Sawant', date: 'June 22, 2026', read: '9 min read' },
  { slug: 'hipaa-penalties-explained', icon: '🏥', tag: 'HIPAA', title: 'HIPAA Penalties in Plain English - What the Fines Actually Look Like', desc: "The quoted number is per violation - and a single failing can be thousands of violations. The four civil tiers by culpability, the criminal penalties up to $250K and ten years, real OCR settlements from Anthem's $16M down to a $650K business associate, and the one missing document that drives the biggest fines.", author: 'Soham Sawant', date: 'June 21, 2026', read: '8 min read' },
  { slug: 'hipaa-privacy-security-breach-rules', icon: '🏥', tag: 'HIPAA', title: 'HIPAA Privacy Rule vs Security Rule vs Breach Notification Rule - Explained', desc: "People say 'HIPAA' as if it were one rule. It's three, dividing the work cleanly: what you may do with PHI (Privacy), how you must protect electronic PHI (Security), and what happens when protection fails (Breach Notification). Each explained, compared side by side, and shown running through a single incident at once.", author: 'Soham Sawant', date: 'June 20, 2026', read: '8 min read' },
  { slug: '18-phi-identifiers-hipaa', icon: '🏥', tag: 'HIPAA', title: 'The 18 PHI Identifiers Under HIPAA - A Complete Reference', desc: "Health data on its own isn't regulated - attach one of eighteen identifiers and it becomes PHI. The complete Safe Harbor list with examples, the identifiers teams miss (dates, ZIP codes, IP addresses, device IDs), Safe Harbor vs Expert Determination, and the re-identification trap that makes 'no names' not enough.", author: 'Soham Sawant', date: 'June 19, 2026', read: '8 min read' },
  { slug: 'what-is-phi-protected-health-information', icon: '🏥', tag: 'HIPAA', title: 'What Is PHI? Protected Health Information Explained With Examples', desc: "A diagnosis is just a fact; a diagnosis attached to a name is a regulated asset. PHI is that second thing. The two-part formula (health detail + identifier), ePHI, clear examples of what is and isn't PHI, and the traps - trackers, 'we stripped the names', mundane fields - that catch product teams.", author: 'Soham Sawant', date: 'June 18, 2026', read: '7 min read' },
  { slug: 'hipaa-explained-startups', icon: '🏥', tag: 'HIPAA', title: 'HIPAA Explained for Startups - What It Is and Who Must Comply', desc: "HIPAA isn't a hospital law - it's a data law. The moment a startup touches protected health information on behalf of a healthcare client, it's in scope. What HIPAA actually is, the three rules in plain English, PHI and the 18 identifiers, covered entities vs business associates, and what compliance really requires.", author: 'Soham Sawant', date: 'June 17, 2026', read: '8 min read' },
  { slug: 'soc2-trust-service-criteria', icon: '📋', tag: 'SOC 2', title: 'Understanding SOC 2 Trust Service Criteria - A Plain-English Guide', desc: "Five categories, one mandatory, and a lot of jargon hiding a simple idea: the criteria are the promises a SOC 2 report tests. Security as the Common Criteria, the four optional categories, the GDPR-isn't-the-Privacy-criterion trap, and why scoping to real commitments beats collecting criteria like trophies.", author: 'Gauri Khatate', date: 'June 17, 2026', read: '6 min read' },
  { slug: 'hipaa-covered-entities-vs-business-associates', icon: '🏥', tag: 'HIPAA', title: 'Does HIPAA Apply to Your Business? Covered Entities vs Business Associates', desc: "The fastest way to misjudge HIPAA is to ask 'are we a hospital?' The real question is whether you create, receive, maintain, or transmit PHI for someone who is. Covered entities, business associates, the subcontractor chain, the narrow conduit exception, and a five-question test for where you stand.", author: 'Soham Sawant', date: 'June 16, 2026', read: '8 min read' },
  { slug: 'continuous-iso-27001-compliance', icon: '♾️', tag: 'ISO 27001', title: 'Continuous ISO 27001 Compliance - Moving from Annual Audit to Always-On', desc: "Certification is a three-year cycle, but the ISMS was never meant to run once a year. How to move from the point-in-time audit scramble to always-on compliance - continuous control monitoring, automated evidence, the daily-to-annual cadence, and surveillance audits that become a formality.", author: 'Soham Sawant', date: 'June 16, 2026', read: '9 min read' },
  { slug: 'soc2-which-type-do-you-need', icon: '📋', tag: 'SOC 2', title: 'SOC 2 Type I vs Type II - Which One Does Your Business Need?', desc: "One is a photograph; the other is a film. Type I tests control design at a point in time; Type II proves operating effectiveness over 3-12 months - which is why enterprise buyers want it. Why 'over a period' is the whole point (SolarWinds), and how to sequence the work once instead of paying for the audit twice.", author: 'Gauri Khatate', date: 'June 15, 2026', read: '6 min read' },
  { slug: 'soc2-vs-iso27001-vs-gdpr', icon: '⚖️', tag: 'SOC 2', title: 'SOC 2 vs ISO 27001 vs GDPR - Key Differences Explained', desc: "Three things companies are told they need, constantly mistaken for one another. One is a report, one is a certificate, one is a law - answering a customer, a market, and a regulator. Why earning one never earns the others, and how to build the shared control core once.", author: 'Gauri Khatate', date: 'June 15, 2026', read: '5 min read' },
  { slug: 'iso-27001-compliance-program-ciso-playbook', icon: '🧭', tag: 'ISO 27001', title: 'Building an ISO 27001 Compliance Program from Scratch - A CISO Playbook', desc: "An ISO 27001 program isn't a binder of policies - it's a management system you run. Context and scope first, then leadership, a real risk assessment, an SoA that traces to risk, and the operating evidence Stage 2 actually tests.", author: 'Soham Sawant', date: 'June 12, 2026', read: '10 min read' },
  { slug: 'iso-27001-cost-india', icon: '💰', tag: 'ISO 27001', title: 'How Much Does ISO 27001 Cost? A Transparent Breakdown for Indian Startups', desc: "The honest answer is ₹6–25 lakh for a first certification - but it splits across five very different buckets: consultant, certification body, tooling, internal time, and the surveillance years. Three sample startup budgets and the hidden costs people forget.", author: 'Soham Sawant', date: 'June 10, 2026', read: '7 min read' },
  { slug: 'gdpr-compliance-program-ciso-playbook', icon: '🇪🇺', tag: 'GDPR', title: 'Building a GDPR Compliance Program from Scratch - A CISO Playbook', desc: "Most programs fail not from doing the wrong things, but from doing them in the wrong order. The sequence that holds - discover, justify, operationalise, secure, govern - and the foundational gaps the record fines were really about.", author: 'Gauri Khatate', date: 'June 9, 2026', read: '5 min read' },
  { slug: 'iso-27001-2022-vs-2013-changes', icon: '🔄', tag: 'ISO 27001', title: 'ISO 27001:2022 Changes vs 2013 - What You Must Update Before Deadline', desc: "The 2022 revision restructured Annex A from 114 controls to 93, regrouped them into four themes, and added 11 new controls for cloud, threat intel, and secure coding. What moved, what your SoA must reflect, and why the 2013 transition deadline has already closed.", author: 'Soham Sawant', date: 'June 8, 2026', read: '9 min read' },
  { slug: 'gdpr-penalties-explained', icon: '⚖️', tag: 'GDPR', title: 'GDPR Penalties Explained - Real Cases and How Companies Failed', desc: "More than €5.88B in fines resolve into four repeatable failures: transfers, lawful basis, rights, and security. The record cases - Meta's €1.2B, Amazon's €746M - and the patterns behind them, each closable before a regulator calls.", author: 'Gauri Khatate', date: 'June 5, 2026', read: '5 min read' },
  { slug: 'automating-iso-27001-compliance', icon: '⚙️', tag: 'ISO 27001', title: 'Automating ISO 27001 Compliance - Tools and What They Actually Cover', desc: "Compliance automation platforms genuinely remove the busywork - continuous control monitoring, evidence collection, policy templates. But scope, the risk assessment, and the SoA are the parts that win the certificate, and no tool decides those for you.", author: 'Soham Sawant', date: 'June 4, 2026', read: '8 min read' },
  { slug: 'how-to-automate-gdpr-compliance', icon: '⚙️', tag: 'GDPR', title: 'How to Automate GDPR Compliance - Tools, Workflows and Architecture', desc: "Manual privacy compliance works until it has to scale or prove itself. How to automate the four obligations that matter - requests, deletion, consent, and the record of processing - around a single source of truth, with the evidence trail generated as a by-product.", author: 'Gauri Khatate', date: 'June 3, 2026', read: '5 min read' },
  { slug: 'iso-42001-explained', icon: '🤖', tag: 'AI Governance', title: "ISO 42001 Explained - The World's First AI Management System Standard", desc: "AI became a governance challenge faster than frameworks could respond. What ISO 42001 requires, who it applies to (including AI users, not just builders), the AI system impact assessment, human oversight, and how it fits alongside ISO 27001 and the EU AI Act.", author: 'Aditya Hadke', date: 'June 2, 2026', read: '13 min read' },
  { slug: 'iso-27001-surveillance-audits', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Surveillance Audits - What They Check and How to Prepare', desc: "Getting certified is the start, not the finish. ISO 27001 runs on a three-year cycle, and surveillance audits keep your certificate alive in years one and two. What they actually check, the always-checked areas, the most common findings, and how to walk in prepared.", author: 'Soham Sawant', date: 'June 2, 2026', read: '8 min read' },
  { slug: 'gdpr-plus-soc-2', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR + SOC 2 - Building a Combined Compliance Strategy', desc: "SOC 2 tells US customers you're secure; GDPR tells European regulators you're lawful. About 80% of the security controls are shared and built once - then the GDPR-only obligations (basis, rights, transfers, notification) run as a deliberate workstream.", author: 'Gauri Khatate', date: 'June 1, 2026', read: '5 min read' },
  { slug: 'iso-27001-plus-soc-2', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 + SOC 2 - How to Get Both Without Doubling the Work', desc: "A certificate and an attestation, different on paper - but built on largely the same controls. How to pursue ISO 27001 and SOC 2 together: the differences that matter, the 40-85% control overlap, which market needs which, and the combined readiness strategy.", author: 'Soham Sawant', date: 'May 29, 2026', read: '10 min read' },
  { slug: 'gdpr-plus-iso-27001', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR + ISO 27001 - How to Align Security and Privacy Controls', desc: "ISO 27001 builds the security machine GDPR demands - but certification is not a privacy shield. Where Article 32 and Annex A overlap, where ISO 27001 stops and GDPR keeps going, and how ISO 27701 bridges the gap on one control set.", author: 'Gauri Khatate', date: 'May 28, 2026', read: '5 min read' },
  { slug: 'iso-27001-plus-dpdp-act', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 + DPDP Act - Overlap Map and Combined Compliance Strategy', desc: "ISO 27001 and India's DPDP Act share a great deal - but not everything. One is a voluntary security certification, the other mandatory privacy law. A control-level overlap map, the DPDP-specific gaps ISO leaves, and the sequencing that lets you build once and demonstrate twice.", author: 'Soham Sawant', date: 'May 27, 2026', read: '10 min read' },
  { slug: 'gdpr-for-hr-employee-data', icon: '👥', tag: 'GDPR', title: 'GDPR for HR and Employee Data - What Companies Must Know', desc: "Employees can't freely consent to their employer, and that single fact rewrites how HR must handle their data. The bases that carry payroll and monitoring, the limits on surveillance, and the €35.3M H&M fine for profiling employees' private lives.", author: 'Gauri Khatate', date: 'May 26, 2026', read: '5 min read' },
  { slug: 'iso-27001-for-it-service-providers', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 for IT Service Providers - Scope, Controls, and Client Trust', desc: "For MSPs and outsourcing firms, ISO 27001 is often the precondition for winning the contract - not a nice-to-have. The multi-client scope challenge, client data segregation, the controls that carry the most audit weight, and how the certificate shortens every sale.", author: 'Soham Sawant', date: 'May 25, 2026', read: '9 min read' },
  { slug: 'gdpr-for-ecommerce', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR for E-commerce - Cookies, Tracking and Customer Data', desc: "The cookie banner is the most-fined surface on the internet. Why prior consent matters, the failures regulators keep penalising, and how to keep conversion without the liability.", author: 'Gauri Khatate', date: 'May 22, 2026', read: '5 min read' },
  { slug: 'iso-27001-for-healthcare', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 for Healthcare - Aligning with HIPAA and Patient Data Rules', desc: "Healthcare data is among the most sensitive and most regulated information any organisation holds. ISO 27001 provides the ISMS backbone that HIPAA, the DPDP Act, and patient data rules can all build on. The control overlaps, the gaps each leaves, and how to build one ISMS for all of them.", author: 'Soham Sawant', date: 'May 21, 2026', read: '9 min read' },
  { slug: 'gdpr-for-healthcare', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR for Healthcare and HealthTech - Managing Sensitive Patient Data', desc: "Health data is the most protected category there is. The breaches that cost the most aren't hackers - they're people inside, looking at records they shouldn't. Article 9, insider threat, access control, and DPIAs.", author: 'Gauri Khatate', date: 'May 20, 2026', read: '5 min read' },
  { slug: 'iso-27001-for-fintech', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 for Fintech - Meeting Regulators and Enterprise Buyers at Once', desc: "Fintech sits between two demanding audiences - financial regulators and enterprise procurement. ISO 27001 is the rare framework that speaks credibly to both. The scope, the controls that carry the most weight, the RBI and sectoral overlaps, and how certification accelerates enterprise sales.", author: 'Soham Sawant', date: 'May 19, 2026', read: '9 min read' },
  { slug: 'gdpr-for-fintech', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR for Fintech - Handling Financial and Sensitive Data Securely', desc: "Financial data isn't a special category under GDPR - and treating it as ordinary is exactly how fintechs get caught. Legal basis, AML retention conflict, and the automated-decision rules that matter.", author: 'Gauri Khatate', date: 'May 18, 2026', read: '5 min read' },
  { slug: 'dpdp-childrens-data', icon: '🇮🇳', tag: 'DPDP Act', title: "DPDP Act and Children's Data - Special Obligations and How to Comply", desc: "If your platform is used by anyone under 18, the DPDP Act treats you differently - and more strictly. Verifiable parental consent, the blanket ban on tracking and targeted advertising to children, the platforms most affected, and a five-step compliance plan.", author: 'Chandrika Mulage', date: 'May 18, 2026', read: '8 min read' },
  { slug: 'iso-27001-for-saas', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 for SaaS Companies - Building Security Into Your Product', desc: "SaaS companies have a different ISO 27001 problem to industrial manufacturers and banks. Multi-tenant infrastructure, shared cloud responsibility, customer data segregation, and DevOps velocity all change which controls matter most. The scope, the controls, and the customer-trust artefacts that complete the certification.", author: 'Soham Sawant', date: 'May 15, 2026', read: '11 min read' },
  { slug: 'gdpr-for-saas', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR for SaaS Companies - What Your Product Needs to Be Compliant', desc: "Why GDPR for SaaS is mostly a product problem - why you are probably a processor, the Article 28 obligations you inherit, and the features buyers expect you to ship.", author: 'Gauri Khatate', date: 'May 14, 2026', read: '7 min read' },
  { slug: 'dpdp-cross-border-data-transfer', icon: '🇮🇳', tag: 'DPDP Act', title: "Cross-Border Data Transfer Under DPDP - What's Allowed and What's Not", desc: "If your company sends Indian user data to servers or vendors outside India, Section 16 of the DPDP Act has something to say about it. Practical implications for cloud users, SaaS-heavy companies, and Significant Data Fiduciaries - plus the architecture decisions that keep your transfer compliance flexible.", author: 'Chandrika Mulage', date: 'May 14, 2026', read: '7 min read' },
  { slug: 'iso-27001-stage-1-vs-stage-2', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Stage 1 vs Stage 2 Audit - What to Expect at Each', desc: "Stage 1 is a documentation review and readiness check. Stage 2 is the effectiveness audit. They are not the same auditor doing the same job twice - they are designed differently, find different things, and require different preparation.", author: 'Soham Sawant', date: 'May 13, 2026', read: '8 min read' },
  { slug: 'gdpr-data-retention-deletion', icon: '🇪🇺', tag: 'GDPR', title: 'Data Retention and Deletion - When and How to Remove Data', desc: "How GDPR storage limitation really works - why there is no universal retention period, how to build a retention schedule from purpose, and how to make deletion reach backups and processors.", author: 'Gauri Khatate', date: 'May 12, 2026', read: '7 min read' },
  { slug: 'dpdp-erasure-deletion-requests', icon: '🇮🇳', tag: 'DPDP Act', title: 'How to Handle Data Deletion (Erasure) Requests Under DPDP', desc: "Erasure is not a support ticket - it is a legal obligation with a compliance trail. The seven-step workflow, the retention obligations that override deletion, and the architecture patterns that make deletion actually reliable.", author: 'Chandrika Mulage', date: 'May 12, 2026', read: '8 min read' },
  { slug: 'iso-27001-certification-timeline', icon: '🌍', tag: 'ISO 27001', title: 'How Long Does ISO 27001 Certification Take? A Realistic Timeline', desc: "ISO 27001 certification takes between four months and eighteen months depending on four variables - team capacity, organisational maturity, scope, and certification body lead times. Three timeline profiles, where projects actually slip, and the surveillance cycle after certification.", author: 'Soham Sawant', date: 'May 11, 2026', read: '7 min read' },
  { slug: 'gdpr-data-breach-response-72-hours', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR Data Breach Response - A 72-Hour Compliance Plan', desc: "A practical GDPR breach response plan - when the 72-hour clock actually starts, which incidents are reportable, what to tell the authority and individuals, and how to document every decision.", author: 'Gauri Khatate', date: 'May 8, 2026', read: '7 min read' },
  { slug: 'dpdp-breach-notification', icon: '🇮🇳', tag: 'DPDP Act', title: 'Data Breach Under DPDP - What to Report, When, and to Whom', desc: "A data breach is already bad. Failing to handle it correctly under the DPDP Act makes it catastrophically worse. The notification timeline, the recipients, what the notice must contain, and the four-phase response plan that holds up under penalty review.", author: 'Chandrika Mulage', date: 'May 8, 2026', read: '8 min read' },
  { slug: 'iso-27001-internal-audit', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Internal Audit - A Practical Step-by-Step Guide', desc: "Clause 9.2 of ISO 27001 mandates that organisations audit their own ISMS - and certification auditors look harder at this than at almost any other clause. The full mechanics of the internal audit, from programme design to corrective action closure.", author: 'Soham Sawant', date: 'May 7, 2026', read: '9 min read' },
  { slug: 'handling-data-subject-requests', icon: '🇪🇺', tag: 'GDPR', title: 'Handling Data Subject Requests - Access, Deletion, Portability', desc: "How to handle GDPR data subject requests in practice - recognising a request, the one-month clock, and how access, erasure, and portability differ in scope and where each goes wrong.", author: 'Gauri Khatate', date: 'May 6, 2026', read: '8 min read' },
  { slug: 'dpdp-privacy-notice-template', icon: '🇮🇳', tag: 'DPDP Act', title: 'DPDP-Compliant Privacy Notice - What It Must Include (With Template)', desc: "Your current privacy policy was probably written for GDPR or as a generic legal cover. Under the DPDP Act you need something sharper - specific, plain, and purpose-tied. The eight mandatory sections, a structured template, and the drafting mistakes that turn a notice into a liability.", author: 'Chandrika Mulage', date: 'May 6, 2026', read: '7 min read' },
  { slug: 'iso-27001-mandatory-documents', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Mandatory Documents and Records - The Complete List', desc: "ISO 27001:2022 requires 14 documents and 12 types of records. The gap between 'we wrote it' and 'we maintain it' is where certification audits go wrong. A clause-by-clause walkthrough with the structuring patterns that actually hold up under audit.", author: 'Soham Sawant', date: 'May 5, 2026', read: '10 min read' },
  { slug: 'dpdp-consent-mechanism-web-app', icon: '🇮🇳', tag: 'DPDP Act', title: 'How to Build a DPDP-Compliant Consent Mechanism on Your Web/App', desc: "Consent is the cornerstone of DPDP compliance - but most Indian websites still collect it the wrong way. Pre-ticked boxes, buried notices, no withdrawal path. The five attributes of valid consent, the four-step flow, and the consent log structure that audits expect.", author: 'Chandrika Mulage', date: 'May 2026', read: '8 min read' },
  { slug: 'gdpr-consent-system', icon: '🇪🇺', tag: 'GDPR', title: 'Building a GDPR-Compliant Consent System (Web and App)', desc: "Why a cookie banner is only ten percent of GDPR consent - the four jobs a consent system must do (capture, store, enforce, prove), and how to build the record first and the banner last.", author: 'Gauri Khatate', date: 'May 2026', read: '8 min read' },
  { slug: 'gdpr-data-mapping-inventory', icon: '🇪🇺', tag: 'GDPR', title: 'Data Mapping and Inventory - Identifying What Data You Collect', desc: "What a GDPR data map really is, why it is the foundation every other obligation depends on, the data you collect without realising it, and the dimensions every record has to answer.", author: 'Gauri Khatate', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-implementation-roadmap', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Implementation Roadmap - From Gap Assessment to Certification', desc: "A practical 7-stage ISO 27001 implementation roadmap from gap assessment to certification. The Stage 1 and Stage 2 audit explained, realistic 9-12 month timelines, common failure points, and the controls most teams underestimate.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-gap-assessment', icon: '🔍', tag: 'ISO 27001', title: 'ISO 27001 Gap Assessment - How to Run One and What to Do With Results', desc: "How to run an ISO 27001 gap assessment that surfaces what the project will cost. The 6-step method, scoring scale, gap register template, and what to do with the findings before Stage 1.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27701-gap-assessment', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 Gap Assessment - How to Run One and What to Do With the Results', desc: "How to run an ISO 27701 gap assessment - who to involve, how to structure it around the control domains, a usable scoring scale, how to present findings, and how to turn the results into a remediation roadmap.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '12 min read' },
  { slug: 'gdpr-compliance-roadmap', icon: '🇪🇺', tag: 'GDPR', title: 'GDPR Compliance Roadmap - A Practical Step-by-Step Guide', desc: "A six-step GDPR compliance roadmap that fits a real product team's quarter. Inventory first, then legal basis, privacy notices, subject rights, security perimeter, and breach response. With 90-day quick-start vs 12-month maturity comparison.", author: 'Gauri Khatate', date: 'April 2026', read: '6 min read' },
  { slug: 'iso-27001-clause-by-clause', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Clause by Clause - What Each Clause Actually Requires', desc: "Plain-English walkthrough of Clauses 4 to 10 - the management system core. What each requires, the documents auditors expect, mandatory documents map, and how each clause is tested in Stage 1 and Stage 2 audits.", author: 'Soham Sawant', date: 'April 2026', read: '12 min read' },
  { slug: 'iso-27701-certification-process', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 Certification Process - Timeline, Stage Audits, and What to Expect', desc: "How the ISO 27701 certification process works end to end - choosing a certification body, Stage 1 and Stage 2 audits, realistic timelines, the surveillance cycle, and the most common failure modes.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '11 min read' },
  { slug: 'consent-under-gdpr', icon: '🇪🇺', tag: 'GDPR', title: 'Consent Under GDPR - What Counts as Valid Consent?', desc: "GDPR Article 4(11) defines consent as freely given, specific, informed, and unambiguous. The four conditions decoded, the symmetrical-withdrawal rule, the proof obligation, and the Planet49 and Google CNIL cases that show what fails the test.", author: 'Gauri Khatate', date: 'April 2026', read: '6 min read' },
  { slug: 'soa-iso-27001-complete-guide', icon: '📋', tag: 'ISO 27001', title: 'Statement of Applicability (SoA) for ISO 27001 - A Complete Guide', desc: "The SoA is the most scrutinised document in your audit. What clause 6.1.3(d) requires, the five mandatory columns, sample SoA entries (included and excluded), the build process, and the mistakes auditors flag most.", author: 'Soham Sawant', date: 'April 2026', read: '11 min read' },
  { slug: 'iso-27701-annex-b-processor-obligations', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 Annex B Controls - Processor-Specific Obligations Unpacked', desc: "Annex B is written for PII processors - SaaS vendors, cloud platforms, payroll bureaus, B2B data services. Seven control areas (B.2 to B.8) explained in operational detail, certification path, and the pitfalls auditors flag most.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '12 min read' },
  { slug: 'gdpr-legal-basis-for-processing', icon: '🇪🇺', tag: 'GDPR', title: 'Legal Basis for Processing - How to Justify Data Collection Under GDPR', desc: "GDPR Article 6 gives you exactly six lawful grounds for processing - and the choice is per-purpose, not per-company. The six bases decoded, why legitimate interests is the most misused, why you cannot switch bases mid-flight, and the Meta €390M case that illustrates the cost.", author: 'Gauri Khatate', date: 'April 2026', read: '6 min read' },
  { slug: 'significant-data-fiduciary-sdf', icon: '🇮🇳', tag: 'DPDP Act', title: 'Significant Data Fiduciary (SDF) - Are You One? What Changes If You Are?', desc: "Section 10 of the DPDP Act reserves a higher tier of obligations for entities handling data at scale. Learn how the government classifies SDFs, the 4 additional obligations that apply, and how to self-assess your SDF exposure.", author: 'Chandrika Mulage', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-scope-definition', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Scope Definition - How to Decide What Goes In and What Stays Out', desc: "The ISMS scope is the most consequential decision before starting ISO 27001. Too broad costs time. Too narrow leaves gaps. Scope examples for SaaS, FinTech, Healthcare, and consulting firms.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27701-annex-a-controls', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 Annex A Controls - A Plain-English Walkthrough for Teams', desc: "Annex A & B controls explained - 8 thematic areas for controllers and processors, key actions for each team, RACI ownership, and practical implementation tips.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '10 min read' },
  { slug: 'consent-under-dpdp-act', icon: '🇮🇳', tag: 'DPDP Act', title: "Consent Under the DPDP Act - What's Valid, What's Not, and How to Implement It", desc: "Section 6 of the DPDP Act sets out 5 non-negotiable pillars of valid consent. Pre-ticked boxes, bundled consent, and vague language will not pass the test. Here is the technical blueprint for DPDP-compliant consent.", author: 'Chandrika Mulage', date: 'April 2026', read: '8 min read' },
  { slug: 'gdpr-data-subject-rights', icon: '🇪🇺', tag: 'GDPR', title: 'Data Subject Rights Under GDPR - What Users Can Ask You to Do', desc: "Eight enforceable rights, 30-day deadlines, and where each breaks operationally. The three you will meet first and how to build the process.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'iso-27001-risk-assessment', icon: '🌍', tag: 'ISO 27001', title: 'Risk Assessment in ISO 27001 - How It Works Step by Step', desc: "The risk assessment is the engine of the ISMS. Step-by-step methodology - asset identification, threat analysis, likelihood-impact scoring, risk treatment, and the risk register with common startup risks.", author: 'Soham Sawant', date: 'April 2026', read: '9 min read' },
  { slug: 'iso-27701-for-data-processors', icon: '🔐', tag: 'ISO 27701', title: 'ISO 27701 for Data Processors - What Third Parties Need to Know', desc: "Clause 9 requirements for data processors - DPAs, sub-processor management, breach notification timelines, Privacy by Design obligations, and the step-by-step certification path.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '12 min read' },
  { slug: '8-rights-data-principals-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: '8 Rights of Data Principals Under the DPDP Act - And How Your Product Must Support Them', desc: "The DPDP Act grants 8 enforceable rights to Data Principals. Failing to operationalise them exposes your organisation to penalties up to ₹250 crore. Here is what each right requires in product terms.", author: 'Chandrika Mulage', date: 'April 2026', read: '9 min read' },
  { slug: 'gdpr-controller-processor-sub-processor', icon: '🇪🇺', tag: 'GDPR', title: 'Data Controller vs Processor vs Sub-Processor - Who Does What?', desc: "Three GDPR roles that decide where legal risk lands. Side-by-side comparison, the dual-role reality for SaaS, and practical steps to get classification right.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'iso-27001-annex-a-controls', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Annex A Controls - All 93 Controls Explained Simply', desc: "93 controls in 4 categories: Organisational (37), People (8), Physical (14), Technological (34). What each covers, the 11 new 2022 controls, how the Statement of Applicability works, and startup priority controls.", author: 'Soham Sawant', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27701-for-data-controllers', icon: '🌐', tag: 'ISO 27701', title: 'ISO 27701 for Data Controllers - Key Requirements and Controls Explained', desc: "If your organisation decides what data to collect, why, and how - you are a PII controller. Clause 7 and Annex B controls in operational detail - legal basis, RoPA, consent, DSR rights, DPIAs, and privacy by design.", author: 'Aditya Hadke', date: 'April 2026', read: '12 min read' },
  { slug: 'data-principal-fiduciary-processor', icon: '🇮🇳', tag: 'DPDP Act', title: "Data Principal vs Data Fiduciary vs Data Processor - Roles Explained Under India's DPDP Act", desc: "The DPDP Act introduces three roles - Data Principal, Data Fiduciary, and Data Processor. Understand who you are in the data ecosystem, what obligations apply, and what happens when one entity holds multiple roles.", author: 'Chandrika Mulage', date: 'April 2026', read: '7 min read' },
  { slug: 'gdpr-business-impact-beyond-fines', icon: '🇪🇺', tag: 'GDPR', title: 'The Real Business Impact of Ignoring GDPR - Beyond Fines', desc: "The fine is 3.7% of total incident cost. The rest: enterprise deal slippage, insurance at 2.8x, customer churn, and engineering velocity loss during retrofit.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'iso-27001-business-value', icon: '🌍', tag: 'ISO 27001', title: 'The Real Business Value of ISO 27001 Certification - Beyond the Badge', desc: "ISO 27001 is not a compliance cost - it is a commercial asset. Enterprise sales acceleration (40% faster), breach cost reduction, 25-30% lower insurance premiums, investor due diligence, and the ROI calculation.", author: 'Soham Sawant', date: 'April 2026', read: '8 min read' },
  { slug: 'how-to-extend-isms-into-pims', icon: '🔐', tag: 'ISO 27701', title: 'How to Extend Your ISMS Into a PIMS - ISO 27001 + ISO 27701', desc: "Most organisations with ISO 27001 have done 50-70% of the ISO 27701 work already. The 7-step extension process, documentation auditors expect, combined vs phased certification, and a PIMS readiness checklist.", author: 'Bhumika Deshmukh', date: 'April 2026', read: '8 min read' },
  { slug: 'what-is-personal-data-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: 'What Counts as Personal Data Under the DPDP Act?', desc: "The DPDP Act's definition is deliberately broad. If you are assuming only Aadhaar or medical records are in scope, you have serious gaps. The breakdown your product and engineering teams need - including the grey zones.", author: 'Chandrika Mulage', date: 'April 2026', read: '6 min read' },
  { slug: 'hidden-data-trails-gdpr', icon: '🇪🇺', tag: 'GDPR', title: 'How Your Product Collects Personal Data Without You Realising', desc: "Session replay, ad pixels, error monitoring, embedded widgets, chat tools - the five hidden collection points in your SaaS stack and why they are a GDPR problem.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'what-is-an-isms', icon: '🌍', tag: 'ISO 27001', title: 'What Is an ISMS? Information Security Management System in Plain English', desc: "An ISMS is not a product, a document, or a one-time project. It is a management system - the PDCA cycle, core components, scope definition, risk assessment, controls, audit, and what an ISMS is NOT.", author: 'Soham Sawant', date: 'April 2026', read: '7 min read' },
  { slug: 'building-a-pims-iso-27701', icon: '🌐', tag: 'ISO 27701', title: 'Building a PIMS - ISO 27701 Implementation Roadmap', desc: "A practical 6-phase roadmap to implement ISO 27701 and build a Privacy Information Management System - from scoping to certification, with realistic timelines, budgets, and common pitfalls.", author: 'Aditya Hadke', date: 'April 2026', read: '10 min read' },
  { slug: 'who-does-dpdp-apply-to', icon: '🇮🇳', tag: 'DPDP Act', title: 'Who Does the DPDP Act Apply To? - A Checklist for Indian Businesses', desc: "For the vast majority of Indian businesses, yes - but the specifics depend on your role, your data, and who your users are. A plain-English checklist plus industry snapshots for SaaS, Fintech, Healthtech, EdTech, and HR software.", author: 'Chandrika Mulage', date: 'April 2026', read: '6 min read' },
  { slug: 'what-counts-personal-data-gdpr', icon: '🇪🇺', tag: 'GDPR', title: 'What Counts as Personal Data Under GDPR? With Real Examples', desc: "The short answer: more than you think. IP addresses, cookie IDs, device IDs, pseudonymous tokens, voice recordings, work emails - all personal data. The surprise table, the combination trap, and anonymous vs pseudonymous.", author: 'Gauri Khatate', date: 'April 2026', read: '5 min read' },
  { slug: 'iso-27001-vs-soc2-vs-gdpr', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 vs SOC 2 vs GDPR - Key Differences Every Business Should Know', desc: "ISO 27001 is a certification. SOC 2 is an attestation report. GDPR is a law. Detailed comparison - scope, geography, cost, audit process, 60-70% control overlap, and which to pursue first.", author: 'Soham Sawant', date: 'April 2026', read: '9 min read' },
  { slug: 'who-needs-iso-27701', icon: '🌐', tag: 'ISO 27701', title: 'Who Needs ISO 27701? - Applicability Guide for Controllers and Processors', desc: "ISO 27701 is applicable to any organisation processing PII. The controller vs processor distinction, industry-by-industry guidance for SaaS, FinTech, Healthtech, and MSPs, plus when formal certification is worth it.", author: 'Aditya Hadke', date: 'April 2026', read: '11 min read' },
  { slug: 'gdpr-vs-dpdp', icon: '⚖️', tag: 'DPDP Act', title: 'GDPR vs DPDP Act: Key Differences Every Indian Company Must Know', desc: "Already GDPR-compliant and treating DPDP as basically the same thing? The lawful basis gap, rights comparison, 22-language requirement, children's threshold at 18, and your exact gap list.", author: 'SecComply', date: 'March 2026', read: '7 min read' },
  { slug: 'gdpr-self-assessment', icon: '🇪🇺', tag: 'GDPR', title: 'Does GDPR Apply to Your Business? A Self-Assessment Guide', desc: "An 8-question self-assessment for startups and SMBs. Score your GDPR exposure, debunk the four exemption myths (no SMB exemption, B2B data is still personal data), and follow the 30-day action plan.", author: 'Gauri Khatate', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27001-self-assessment', icon: '✅', tag: 'ISO 27001', title: 'Does ISO 27001 Apply to Your Business? A Self-Assessment Guide', desc: "Work through 6 triggers to decide whether ISO 27001 applies right now - enterprise customers, international expansion, sensitive data, investor due diligence, DPDP Act, and prior incidents. Includes a scoring guide and 5-phase roadmap.", author: 'Soham Sawant', date: 'April 2026', read: '10 min read' },
  { slug: 'iso-27701-vs-gdpr-vs-dpdp', icon: '🌐', tag: 'ISO 27701', title: 'ISO 27701 vs GDPR vs DPDP - How They Overlap and Where They Differ', desc: "A SaaS company in India processing EU and Indian data faces three frameworks simultaneously. The detailed comparison - cross-border transfers, consent, breach timelines, and how to run a single unified compliance programme.", author: 'Aditya Hadke', date: 'April 2026', read: '13 min read' },
  { slug: 'dpdp-act-2023-explained', icon: '🇮🇳', tag: 'DPDP Act', title: 'DPDP Act 2023 Explained in Plain English', desc: "India's data privacy law is now enforceable. Who it applies to (no size threshold), 5 core obligations, the penalty schedule up to ₹250 crore, the 4 terms you must know, and your first 30 days action plan.", author: 'SecComply', date: 'March 2026', read: '7 min read' },
  { slug: 'gdpr-explained-startups', icon: '🇪🇺', tag: 'GDPR', title: "GDPR Explained for Startups - What It Is, Why It Matters, and What You Must Do About It", desc: "Most founders think GDPR applies only at scale. The fines say otherwise. Six principles, controller vs processor, eight user rights, the consent trap, real-world cases (Spotify, Meta, Clearview AI), and the practical startup checklist.", author: 'Gauri Khatate', date: 'April 2026', read: '8 min read' },
  { slug: 'iso-27001-explained-startups', icon: '🌍', tag: 'ISO 27001', title: 'ISO 27001 Explained for Startups - What It Is and Why It Matters', desc: "Enterprise customers ask for it. Investors flag it in due diligence. What ISO 27001 actually requires, the 93 Annex A controls, the 5-phase certification process, realistic cost (₹8–25L) and timeline (4–9 months), and ISO 27001 vs SOC 2.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'iso-27701-explained', icon: '🔐', tag: 'Privacy Compliance', title: 'ISO 27701 Explained: Privacy Information Management for Compliance Teams', desc: "ISO 27701 is the privacy extension to ISO 27001. What a PIMS requires, PII controller vs processor controls, the RoPA, privacy by design, data subject rights, regulatory mapping to GDPR and DPDP, and a 6-9 month implementation roadmap.", author: 'Aditya Hadke', date: 'March 2026', read: '12 min read' },
  { slug: 'data-protection-officer-dpo-dpdp', icon: '🇮🇳', tag: 'DPDP Act', title: 'What Is a Data Protection Officer (DPO) Under the DPDP Act - Do You Need One?', desc: "The DPO role under the DPDP Act is structured, targeted, and demanding - but only mandatory for Significant Data Fiduciaries. The full picture on the role, reporting structure, India-presence requirement, and when you need one.", author: 'Chandrika Mulage', date: 'April 2026', read: '7 min read' },
  { slug: 'dpdp-applicability-quiz-walkthrough', icon: '🇮🇳', tag: 'DPDP Act', title: 'Do I Need to Comply? - DPDP Act Applicability Quiz Walkthrough', desc: "A structured 7-question walkthrough to self-assess DPDP Act applicability and your compliance tier. Covers exemptions, volume thresholds, cross-border considerations, and an immediate action plan.", author: 'Chandrika Mulage', date: 'April 2026', read: '9 min read' },
  { slug: 'grc-automation', icon: '⚙️', tag: 'Compliance Governance', title: 'GRC Automation: The Future of Compliance', desc: "The compliance team that runs on spreadsheets is running a programme designed for 2010. What GRC automation actually does, what it cannot replace, how to evaluate platforms (Vanta, Drata, Sprinto, Secureframe), and when to invest.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'supply-chain-attacks-solarwinds', icon: '🔗', tag: 'Supply Chain Security', title: 'Supply Chain Attacks: Lessons from SolarWinds', desc: "18,000 organisations downloaded a backdoor disguised as a routine update. The full kill chain, 14-month dwell time, 6 lessons every security team must apply, the SBOM imperative, and what your controls must look like now.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'vulnerability-disclosure-policy', icon: '🔍', tag: 'Security Governance', title: 'How to Build a Vulnerability Disclosure Policy', desc: "Every day researchers find vulnerabilities in systems they don't own. Without a VDP they have no safe way to tell you. Scope, safe harbour clause, security.txt file, triage SLAs, and ISO 27001 compliance mapping.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'how-to-write-security-policy', icon: '📋', tag: 'Security Governance', title: 'How to Write a Security Policy People Will Actually Follow', desc: "Most security policies are written to satisfy auditors, not change behaviour. The 6-step process, before/after language rewrites, 8 policy types, enforcement mechanisms, and compliance mapping for ISO 27001, SOC 2, and DPDP.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'owasp-top-10-2025', icon: '🔓', tag: 'AppSec', title: 'OWASP Top 10 - 2025 Edition Breakdown', desc: "All 10 categories with CWE references, real-world examples, fix guidance, and compliance mapping. SSRF elevated to standalone category. AI-generated code security guidance added for the first time.", author: 'Soham Sawant', date: 'March 2026', read: '10 min read' },
  { slug: 'tprm-best-practices', icon: '🔗', tag: 'Vendor Risk', title: 'Third-Party Risk Management Best Practices', desc: "62% of breaches are traced to a third party. Vendor tiering, access scoping, contractual controls, continuous monitoring, and the offboarding gap. With Target, Okta, British Airways, and M&S breach cases.", author: 'Gauri Khatate', date: 'March 2026', read: '7 min read' },
  { slug: 'red-team-vs-blue-team', icon: '🔴', tag: 'Security Testing', title: "Red Team vs Blue Team: What's the Difference and Why You Need Both", desc: "Four real-world breach cases, the Purple Team model, MTTD improvement, and how to decide which your organisation needs first.", author: 'Gauri Khatate', date: 'March 2026', read: '7 min read' },
  { slug: 'tabletop-security-exercise', icon: '🎯', tag: 'Incident Response', title: 'How to Run a Tabletop Security Exercise', desc: "77% of organisations that suffered a breach had no tested IR plan. Scenario selection, 6 ransomware injects, participant roles, debrief structure, and compliance evidence for ISO 27001, SOC 2, and HIPAA.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'phishing-simulation-guide', icon: '🎣', tag: 'Security Awareness', title: 'Phishing Simulation: A Step-by-Step Guide', desc: "36% of all breaches involve phishing. A well-run simulation cuts click rates by 80% in 12 months. The 7-step process, 5 template types, 4 metrics, and the compliance evidence auditors actually want.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'encryption-at-rest-vs-in-transit', icon: '🔐', tag: 'Data Security', title: 'Encryption at Rest vs In Transit: What You Must Know', desc: "AES-256 vs TLS 1.3, key management done right, compliance requirements across 6 frameworks, and the implementation mistakes that get organisations into trouble with auditors.", author: 'Soham Sawant', date: 'March 2026', read: '7 min read' },
  { slug: 'cspm-aws', icon: '☁️', tag: 'Cloud Security', title: 'Cloud Security Posture Management for AWS', desc: "99% of cloud breaches stem from misconfiguration. What CSPM does on AWS, the top misconfigurations it catches, ISO 27001 and SOC 2 compliance mapping, and a 5-step implementation guide.", author: 'Soham Sawant', date: 'March 2026', read: '8 min read' },
  { slug: 'ciso-startup-guide', icon: '🛡️', tag: 'Security Leadership', title: 'The Role of a CISO in a Startup', desc: "Most startups think they need a CISO when they get hacked. The ones that get it right hire one so they never do. What a CISO actually does, when to hire one, and the full-time vs vCISO breakdown.", author: 'Soham Sawant', date: 'June 2025', read: '5 min read' },
  { slug: 'devsecops-shifting-left', icon: '⚙️', tag: 'DevSecOps', title: 'DevSecOps: Shifting Security Left Without Slowing Down', desc: "3 pillars, the complete automation stack (SAST, SCA, DAST, IaC), STRIDE threat modeling, compliance integration, and a 3-phase maturity roadmap.", author: 'Aditya Hadke', date: 'March 2025', read: '12 min read' },
  { slug: 'how-to-prepare-for-a-security-audit', icon: '🔍', tag: 'Audit Readiness', title: 'How to Prepare for a Security Audit', desc: "8 stages, the evidence auditors actually look for, and a pre-audit checklist covering ISO 27001, SOC 2, DPDPA, and GDPR.", author: 'Bhumika Deshmukh', date: 'March 2026', read: '7 min read' },
  { slug: 'security-metrics-board-reporting', icon: '📊', tag: 'Security Governance', title: 'Security Metrics That Actually Matter to the Board', desc: "Six metric categories, five governance questions, and the reporting principles that change what happens in that boardroom.", author: 'Bhumika Deshmukh', date: 'March 2026', read: '8 min read' },
  { slug: 'sbom-software-bill-of-materials', icon: '📦', tag: 'Supply Chain Security', title: 'SBOM 101: Why Software Bills of Materials Matter', desc: 'Log4Shell exposed 625,000+ apps using a library nobody knew they had. What SBOMs are, SPDX vs CycloneDX, and how to generate one today.', author: 'Soham Sawant', date: 'March 20, 2026', read: '8 min read' },
  { slug: 'vulnerability-management-startups', icon: '🔍', tag: 'Vulnerability Management', title: 'Vulnerability Management for Startups: A Practical Guide', desc: "Core process, CVSS severity framework, free tools, and a 90-day roadmap to audit-readiness without a large security team.", author: 'Aditya Hadke', date: 'March 2026', read: '8 min read' },
  { slug: 'cloud-native-security', icon: '☁️', tag: 'Cloud Security', title: 'Cloud-Native Security: Key Concepts Every Team Must Know', desc: 'From containers to microservices, Zero Trust to DevSecOps - securing modern cloud-native environments across ISO 27001, SOC 2, HIPAA, and GDPR.', author: 'Soham Sawant', date: 'June 2025', read: '6 min read' },
  { slug: 'how-to-evaluate-security-vendor', icon: '🛡️', tag: 'Vendor Risk', title: 'How to Evaluate Your Security Vendor Without Getting Burned', desc: "The right questions, red flags, certifications table, and contract clauses that protect you when things go wrong.", author: 'Aditya Hadke', date: 'March 2026', read: '7 min read' },
  { slug: 'ai-generated-code-security-risks', icon: '🤖', tag: 'AI Security', title: 'AI-Generated Code and Security Risks', desc: '3 in 5 AI code suggestions contain at least one flaw. Where the risk lives and how to build the review layer that makes AI-speed development safe.', author: 'Gauri Khatate', date: 'March 2026', read: '5 min read' },
  { slug: 'top-5-cloud-misconfigurations', icon: '☁️', tag: 'Cloud Security', title: 'Top 5 Cloud Misconfigurations and How to Fix Them', desc: "The five misconfigurations that appear most often in breach investigations, with exact fixes for each.", author: 'Bhumika Deshmukh', date: 'March 11, 2026', read: '7 min read' },
  { slug: 'soc2-type1-vs-type2', icon: '📋', tag: 'SOC 2', title: 'SOC 2 Type I vs Type II - The Distinction That Actually Matters', desc: 'One is a snapshot. The other is proof over time. What separates them and the practical path from one to the other.', author: 'Gauri Khatate', date: 'March 2026', read: '5 min read' },
  { slug: 'top-security-tools-startup', icon: '🔐', tag: 'Security Tools', title: 'Top 10 Security Tools Every Startup Should Know in 2026', desc: 'Ten tools in deployment order, each one closes a SOC 2 gap and builds enterprise trust. Several are free.', author: 'Bhumika Deshmukh', date: 'March 2026', read: '8 min read' },
  { slug: 'soc2-vs-iso27001', icon: '📋', tag: 'Compliance Guide', title: 'SOC 2 vs ISO 27001: Which Certification Should You Choose?', desc: 'Cost, timeline, market fit, and the honest recommendation for Indian startups and SaaS companies expanding globally.', author: 'SecComply', date: 'March 2026', read: '9 min read' },
  { slug: 'what-is-cspm-scan', icon: '☁️', tag: 'Cloud Security', title: 'What is a CSPM Scan? Cloud Security Posture Management Explained', desc: 'How CSPM scans work, what they detect, and how to stay continuously compliant across AWS, Azure, and GCP.', author: 'SecComply', date: 'March 2025', read: '7 min read' },
  { slug: 'skt-breach-compliance-failure', icon: '📡', tag: 'Breach Analysis', title: "SK Telecom Breach: When Compliance Failures Become a $97M Bill", desc: "South Korea's biggest telecom wasn't brought down by a zero-day - it was missing basics. What every organisation should take from the $97M fine.", author: 'SecComply', date: 'March 2026', read: '10 min read' },
  { slug: 'dpdp-act-indian-startups', icon: '🇮🇳', tag: 'DPDP Act', title: 'DPDP Act 2023: What Indian Startups Need to Know', desc: "A breakdown of India's Digital Personal Data Protection Act and practical steps for compliance readiness.", author: 'SecComply', date: 'March 2025', read: '6 min read' },
  { slug: 'top-10-security-controls', icon: '🔒', tag: 'Security Controls', title: 'Top 10 Security Controls Every Startup Should Implement', desc: 'Essential security controls that form the foundation of any compliance program, explained in plain language.', author: 'SecComply', date: 'February 2025', read: '5 min read' },
  { slug: 'cost-of-non-compliance', icon: '💰', tag: 'Compliance', title: 'The True Cost of Non-Compliance in 2025', desc: 'Data-driven analysis of what compliance failures cost companies, from fines to lost deals and reputation damage.', author: 'SecComply', date: 'January 2025', read: '6 min read' },
]
export default function Blog() {
  return (
    <Layout>
      <Head>
        <title>Blog & Insights, SecComply</title>
        <meta name="description" content="Latest insights on cybersecurity, compliance trends, and regulatory updates from the SecComply team." />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/assets/css/resource-pages.css" />
      </Head>

      <style jsx global>{`
        .blog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;max-width:1100px;margin:40px auto 80px;padding:0 24px}
        .blog-card{background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;transition:all .3s ease;text-decoration:none;color:inherit;position:relative;overflow:hidden}
        .blog-card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#FF6000,#FF8A3D);transform:scaleX(0);transform-origin:left;transition:transform .4s cubic-bezier(.16,1,.3,1)}
        .blog-card:hover::before{transform:scaleX(1)}
        .blog-card:hover{border-color:rgba(255, 96, 0,.3);transform:translateY(-4px);box-shadow:0 12px 40px rgba(255, 96, 0,.1)}
        .blog-tag{display:inline-block;padding:4px 12px;border-radius:20px;font-size:.68rem;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;background:rgba(255, 96, 0,.12);color:#FF6000;width:fit-content}
        .blog-icon{font-size:1.6rem;line-height:1}
        .blog-card h3{font-size:1rem;font-weight:700;color:#F8FAFC;margin:0;line-height:1.4}
        .blog-card p{font-size:.86rem;color:#94A3B8;line-height:1.6;margin:0;flex:1}
        .blog-meta{font-size:.75rem;color:#64748B;display:flex;align-items:center;gap:8px;flex-wrap:wrap}
        .blog-meta .dot{opacity:.4}
        .blog-cta{color:#FF6000;font-size:.85rem;font-weight:600;display:inline-flex;align-items:center;gap:5px;transition:gap .2s;margin-top:4px}
        .blog-card:hover .blog-cta{gap:9px}
        @media(max-width:900px){.blog-grid{grid-template-columns:repeat(2,1fr)}}
        @media(max-width:600px){.blog-grid{grid-template-columns:1fr;padding:0 16px}}
      `}</style>

      <section className="sub-hero">
        <Link href="/resources" className="sub-back">← Back to Resources</Link>
        <h1>📝 Blog & Insights</h1>
        <p>Latest insights on cybersecurity, compliance trends, and regulatory updates.</p>
      </section>

      <div className="blog-grid">
        {posts.map((post) => (
          <Link key={post.slug} href={'/resources/blog/' + post.slug} className="blog-card">
            <span className="blog-tag">{post.tag}</span>
            <div className="blog-icon">{post.icon}</div>
            <h3>{post.title}</h3>
            <p>{post.desc}</p>
            <div className="blog-meta">
              <span>{post.author}</span>
              <span className="dot">·</span>
              <span>{post.date}</span>
              <span className="dot">·</span>
              <span>{post.read}</span>
            </div>
            <span className="blog-cta">Read article →</span>
          </Link>
        ))}
      </div>
    </Layout>
  )
}